config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :users
  resources :sessions
  resources :recipes

  root "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create", via: :get
  match "/signin", to: "sessions#new", as: :sign_in, via: :get
  match "/signout", to: "sessions#destroy", as: :sign_out, via: :delete

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications
  has_many :recipes
  has_many :m_recipes, through: :recipes

  class << self
    def find_or_create_with_omniauth omniauth, current_user = nil
      return nil unless Authentication::PROVIDERS.include? omniauth.provider
      transaction do
        if current_user
          if authentication = current_user.authentications.find_by(params_to_find(omniauth))
            authentication.update_attributes! authentication_params(omniauth)
          else
            current_user.authentications.create! authentication_params(omniauth)
          end
          user = current_user.update_attributes! user_params(omniauth)
        else
          if authentication = Authentication.find_by(params_to_find(omniauth))
            user = authentication.user
          else
            user = User.create! user_params(omniauth)
            user.authentications.create! authentication_params(omniauth)
          end
        end
        user
      end
    rescue
    end

    private

    def params_to_find omniauth
      case omniauth.provider
      when "google_oauth2"
        {
          provider: omniauth.provider,
          username: omniauth.uid.to_s
        }
      when "twitter"
        {
          provider: omniauth.provider,
          username: omniauth.info.nickname
        }
      when "instagram"
        {
          provider: omniauth.provider,
          username: omniauth.info.nickname
        }
      when "dropbox_oauth2"
        {
          provider: omniauth.provider,
          username: omniauth.uid.to_s
        }
      end
    end

    def user_params omniauth
      case omniauth.provider
      when "google_oauth2"
        {
          name: omniauth.info.name,
          photo: omniauth.info.image,
          mail: omniauth.info.email
        }
      when "twitter"
        {
          name: omniauth.info.name,
          photo: omniauth.info.image
        }
      when "instagram"
        {
          name: omniauth.info.name,
          photo: omniauth.info.image
        }
      when "dropbox_oauth2"
        {
          name: omniauth.info.name,
          photo: Settings.default_profile_image,
          mail: omniauth.info.email
        }
      end
    end

    def authentication_params omniauth
      case omniauth.provider
      when "google_oauth2"
        {
          provider: omniauth.provider,
          platform_id: omniauth.uid,
          username: omniauth.uid,
          access_token: omniauth.credentials.token,
          refresh_token: omniauth.credentials.refresh_token,
          expires_at: Time.at(omniauth.credentials.expires_at.to_i)
        }
      when "twitter"
        {
          provider: omniauth.provider,
          platform_id: omniauth.uid,
          username: omniauth.info.nickname,
          access_token: omniauth.credentials.token,
          secret_token: omniauth.credentials.secret
        }
      when "instagram"
        {
          provider: omniauth.provider,
          platform_id: omniauth.uid,
          username: omniauth.info.nickname,
          access_token: omniauth.credentials.token
        }
      when "dropbox_oauth2"
        {
          provider: omniauth.provider,
          platform_id: omniauth.uid.to_s,
          username: omniauth.uid.to_s,
          access_token: omniauth.credentials.token
        }
      end
    end
  end

  def google_client
    authentication = authentications.find_by(provider: "google_oauth2")
    access_token = authentication.try(:access_token)
    refresh_token = authentication.try(:refresh_token)
    return nil unless access_token && refresh_token

    @google_client ||= Google::APIClient.new
    @google_client.authorization.access_token = access_token

    # refresh token
    if authentication.expires_at <= Time.current + 5.minutes
      @google_client.authorization.client_id = ENV["GOOGLE_CLIENT_ID"]
      @google_client.authorization.client_secret = ENV["GOOGLE_CLIENT_SECRET"]
      @google_client.authorization.refresh_token = refresh_token
      @google_client.authorization.grant_type = "refresh_token"
      auth = @google_client.authorization.fetch_access_token!
      @google_client.authorization.access_token = auth["access_token"]
      authentication.update_attributes access_token: auth["access_token"],
        expires_at: Time.current + auth["expires_in"].to_i
    end

    @google_client
  end

  def twitter_client
    access_token = authentications.find_by(provider: "twitter").try(:access_token)
    secret_token = authentications.find_by(provider: "twitter").try(:secret_token)
    return nil unless access_token && secret_token

    @twitter_client ||= Twitter::REST::Client.new do |config|
      config.consumer_key = ENV["TWITTER_CONSUMER_KEY"]
      config.consumer_secret = ENV["TWITTER_CONSUMER_SECRET"]
    end
    @twitter_client.access_token = access_token
    @twitter_client.access_token_secret = secret_token
    @twitter_client
  end

  def instagram_client
    access_token = authentications.find_by(provider: "instagram").try(:access_token)
    return nil unless access_token

    @instagram_client ||= Instagram.client
    @instagram_client.access_token = access_token
    @instagram_client
  end

  def dropbox_client
    access_token = authentications.find_by(provider: "dropbox_oauth2").try(:access_token)
    return nil unless access_token

    DropboxClient.new(access_token)
  end

  def connected? provider
    if provider.is_a?(Array)
      provider.all? { |p| connected? p }
    else
      authentications.find_by(provider: provider) ? true : false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, :check_user, only: :show

  def show
    @m_recipes = M::Recipe.where(multiple: true).to_a +
      (M::Recipe.where(multiple: false).to_a - current_user.m_recipes)
    @recipes = current_user.recipes
  end

  private

  def check_user
    redirect_to user_path(current_user) if current_user.id != params[:id].to_i
  end
end

app/views/users/_connections.html.erb
<script>
  var twitterConnected = <%= current_user.connected?("twitter") ? 1 : 0 %>;
  var instagramConnected = <%= current_user.connected?("instagram") ? 1 : 0 %>;
  var googleConnected = <%= current_user.connected?("google_oauth2") ? 1 : 0 %>;
</script>

app/views/users/_m_recipes.html.erb
<div class="text-center">
  <h2>Available recipes</h2>
  <br/><br/>
</div>
<table class="table table-hover recipes">
  <tbody>
    <% @m_recipes.each do |m_recipe| %>
      <% partial = m_recipe.m_id == 1 ? "recipes/new_with_modal" : "recipes/new_without_modal" %>
      <%= render partial: partial, locals: { m_recipe: m_recipe } %>
    <% end %>
  </tbody>
</table>
<%= render "recipes/forms/m_id_1" if @m_recipes.detect { |m_recipe| m_recipe.m_id == 1} %>

app/views/users/_recipes.html.erb
<% if @recipes.present? %>
<div class="text-center">
  <br/><br/>
  <h2>Enabled recipes</h2>
  <br/><br/>
</div>
<table class="table table-hover recipes">
  <tbody>
    <% @recipes.each do |recipe| %>
    <tr>
      <td width="20%"><%= image_tag recipe.m_recipe.image %></td>
      <td width="70%">
        <h3><%= recipe.m_recipe.description %></h3>
        <% if recipe.m_recipe.m_id == 1 %>
          <%= recipe.object %> (<%= recipe.executes_at %>)
        <% end %>
      </td>
      <td width="10%">
        <%= link_to "Disable", recipe_path(recipe), method: :delete,
          data: { confirm: "Do you really want to disable this recipe ?" }, class: "btn btn-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/users/show.html.erb
<%= render "connections" %>
<br/><br/><br/>
<div class="text-center">
  <%= image_tag "logo.png" %>
  <br/><br/><br/>
  <%= link_to "/auth/instagram" do %>
  <button class="btn btn-lg btn-instagram <%= connect_button_class "instagram" %>">
    <i class="fa fa-instagram"></i> | <%= current_user ? "Connect" : "Signin" %> with Instagram
  </button>
  <% end %>
  <%= link_to "/auth/twitter" do %>
  <button class="btn btn-lg btn-twitter <%= connect_button_class "twitter" %>">
    <i class="fa fa-twitter"></i> | <%= current_user ? "Connect" : "Signin" %> with Twitter
  </button>
  <% end %>
  <%= link_to "/auth/google_oauth2" do %>
  <button class="btn btn-lg btn-google-plus <%= connect_button_class "google_oauth2" %>">
    <i class="fa fa-google-plus"></i> | <%= current_user ? "Connect" : "Signin" %> with Google
  </button>
  <% end %>
  <%= link_to "/auth/dropbox_oauth2" do %>
  <button class="btn btn-lg btn-dropbox <%= connect_button_class "dropbox_oauth2" %>">
    <i class="fa fa-dropbox"></i> | <%= current_user ? "Connect" : "Signin" %> with Dropbox
  </button>
  <% end %>
  <br/><br/>
</div>
<%= render "m_recipes" %>
<%= render "recipes" %>
<br/><br/><br/>