config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :users
  resources :sessions
  resources :recipes

  root "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create", via: :get
  match "/signin", to: "sessions#new", as: :sign_in, via: :get
  match "/signout", to: "sessions#destroy", as: :sign_out, via: :delete

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/_header.html.erb
<nav class="navbar-inverse navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">IFTTT</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <% if current_user %>
      <ul class="nav navbar-nav navbar-right">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag current_user.photo, size: "20x20" %>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to t("helpers.links.sign_out"), sign_out_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IFTTT Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= bootstrap_flash %>
    <%= yield %>
  </div>
</body>
</html>